### ISSUE TITLE
support the DiT architecture and the CIFAR-10 dataset

### ISSUE THREAD

**Issue by zhuyyx** [xandergos/sCM-mnist#3]
Do you have plans to support the DiT architecture and the CIFAR-10 dataset, or reproduce the results from the paper?

**Comment by xandergos** [comment]
The primary purpose of this repository is to serve as a reference for the algorithm. I don't have the compute to reproduce the results from the paper unfortunately, but for what its worth, I've repurposed this code for one of my other projects and have found that two-step generation has an FID within about 20% of the diffusion model's FID. This is very close to what the paper claims for ImageNet.

As for DiT and CIFAR-10, I don't intend to modify this repository to support them, but it should be pretty straightforward to modify the code for your own purposes, if that is desired. It's just a matter of swapping `dataset` to use CIFAR-10 and loading DiT instead of a UNet for `model`.
